//requirejs的配置操作
require.config({
	baseUrl:"/",
	paths:{
		"jquery":"lib/jquery/jquery-1.12.4.min",
		"cookie":"lib/jquery_plugins/jquery.cookie",
		"arttemplate":"lib/arttemplate/template-native",
		"load":"js/loadheaderfooternav",
		"lunbo":"js/js",
		"tool":"js/tools",
		"regist":"js/regist",
		"login":"js/login"
	}
})
